services:
  kai-db:
    image: postgres:15-alpine
    container_name: kai-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

  kai-redis:
    image: redis:alpine
    container_name: kai-redis
    restart: always

  kai-guacd:
    image: guacamole/guacd
    container_name: kai-guacd
    restart: always

  kai-guacamole:
    image: guacamole/guacamole
    container_name: kai-guacamole
    environment:
      - GUACD_HOSTNAME=kai-guacd
      - GUACD_PORT=4822
      - GUACAMOLE_HOME=/etc/guacamole
      - HTTP_AUTH_ENABLED=true
      - HTTP_AUTH_HEADER=X-Guacamole-User
      - POSTGRESQL_ENABLED=true
      - POSTGRESQL_HOSTNAME=kai-db
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=guacamole_db
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./guacamole_config:/etc/guacamole
    depends_on:
      - kai-guacd
      - kai-db
    restart: always

  kai-app:
    build: .
    container_name: kai-app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@kai-db:5432/${POSTGRES_DB}
    volumes:
      - ./static/scans:/app/static/scans
      - ./static/templates:/app/static/templates
      - ./backups:/app/backups
    depends_on:
      - kai-db
      - kai-redis
    restart: always
